### ISSUE TITLE
[BUG]: 0.9.0 crashes with "job does not define a strategy or interior matrix"

### ISSUE THREAD

**Issue by Nateowami** [woodruffw/zizmor#283]
### Pre-submission checks

- [X] I am **not** filing a feature request. These should be filed via the feature request form instead.
- [X] I have looked through the [open issues](https://github.com/woodruffw/zizmor/issues?q=is%3Aissue+is%3Aopen+) for a duplicate report.

### Expected behavior

Given this workflow file, zizmor 0.8.0 handles it fine:
``` yaml
name: Workflow

on:
  workflow_call:
    inputs:
      os:
        type: string

jobs:
  deploy:
    runs-on: ${{inputs.os}}
    steps:
      - run: echo "Hello world"
```

### Actual behavior

zizmor 0.9.0 crashes with this message:
>self-hosted-runner failed on release.yml
>
>Caused by:
>    job does not define a strategy or interior matrix

### Reproduction steps

1. Run `zizmor --version` to verify version is `0.9.0`
2. Save the YAML file above as `release.yml`
3. Run `zizmor release.yml`
4. Observe the error
