### ISSUE TITLE
[BUG]: credential persistence through GitHub Actions artifacts

### ISSUE THREAD

**Issue by dcampbell24** [woodruffw/zizmor#290]
### Pre-submission checks

- [X] I am **not** filing a feature request. These should be filed via the feature request form instead.
- [X] I have looked through the [open issues](https://github.com/woodruffw/zizmor/issues?q=is%3Aissue+is%3Aopen+) for a duplicate report.

### Expected behavior

It should tell you that you need
```yml
        uses: actions/checkout@v4
        with:
          persist-credentials: false
```

### Actual behavior

Instead of
```yml
   |
15 |         - name: "Checkout repo"
   |  _________-
16 | |         uses: actions/checkout@v4
   | |_________________________________- does not set persist-credentials: false
   |
```

### Reproduction steps

1. Missing `persist-credentials: false`
2. Run zizmor
