### ISSUE TITLE
[BUG]: v1.1.0 regression

### ISSUE THREAD

**Issue by Jayllyz** [woodruffw/zizmor#431]
### Pre-submission checks

- [X] I am **not** filing a feature request. These should be filed via the feature request form instead.
- [X] I have looked through the [open issues](https://github.com/woodruffw/zizmor/issues?q=is%3Aissue+is%3Aopen+) for a duplicate report.

### Expected behavior

<img width="1037" alt="Capture d’écran 2025-01-13 à 10 08 24" src="https://github.com/user-attachments/assets/3b67e045-353f-43f5-b0f2-277f7bad843e" />

### Actual behavior

Run no longer works on the same file after updating to v1.1.0
<img width="875" alt="Capture d’écran 2025-01-13 à 10 07 47" src="https://github.com/user-attachments/assets/5fc7ab8c-3255-4a6d-a46f-b8e38b2170e4" />

### Reproduction steps

Here is my release workflow which reproduce the issue

```yaml
name: Release

on:
  workflow_dispatch:
    inputs:
      publish-tag:
        description: 'The tag to publish'
        required: true
        type: string

concurrency:
  group: release

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Install Rust toolchain
      uses: moonrepo/setup-rust@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check and Test
      run: cargo check --all-targets --all-features && cargo test

    - name: Tag the version
      env:
        GIT_TAG: ${{ inputs.publish-tag }}
      run: |
        git tag "${GIT_TAG}"
        git push origin "${GIT_TAG}"

    - name: Generate a changelog
      uses: orhun/git-cliff-action@v4
      id: git-cliff
      with:
        config: cliff.toml
        args: -vv --latest --strip header
      env:
        OUTPUT: CHANGES.md
        GITHUB_REPO: ${{ github.repository }}

    - name: Create github release
      uses: taiki-e/create-gh-release-action@v1 # zizmor: ignore[ref-confusion]
      with:
        branch: main
        changelog: CHANGES.md
        ref: refs/tags/${{ inputs.publish-tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-binary:
    name: Run the build-binaries workflow
    needs:
    - create-release
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-binaries.yaml
    with:
      publish-tag: ${{ inputs.publish-tag }}
```
