### ISSUE TITLE
[BUG]:  overly broad permissions on usage of reusable workflows

### ISSUE THREAD

**Issue by notdodo** [woodruffw/zizmor#540]
### Pre-submission checks

- [x] I am **not** filing a feature request. These should be filed via the feature request form instead.
- [x] I have looked through the [open issues](https://github.com/woodruffw/zizmor/issues?q=is%3Aissue+is%3Aopen+) for a duplicate report.

### Expected behavior

zizmor shouldn't notify "overly broad permissions" if the permissions are set on the reusable workflow steps.

### Actual behavior

When a reusable workflow, with permissions set, is used in an actual workflow zizmor reports:

![Image](https://github.com/user-attachments/assets/89f2b05a-4960-4b33-8461-8ba3e12f5a35)

### Reproduction steps

Reusable workflow: https://github.com/notdodo/github-actions/blob/main/.github/workflows/clean-branch-cache.yml
The `permissions` are set at job level

```yaml
jobs:
  cleanup:
    name: Cleanup caches for a merged branch
    runs-on: ${{ inputs.runs-on }}
    permissions:
      actions: write
```

Running workflow: https://github.com/notdodo/github-actions/blob/main/.github/workflows/repo-branch-cleanup.yml
The workflow just uses the reusable workflow.

### Logs

```plain text

```

### Additional context

Zizmor workflow: https://github.com/notdodo/github-actions/blob/main/.github/workflows/infra-security-scan.yml#L71
