### ISSUE TITLE
Feature: secrets-inherit flipside

### ISSUE THREAD

**Issue by alexanderkjall** [woodruffw/zizmor#579]
### Pre-submission checks

- [x] I am **not** reporting a bug (crash, false positive/negative, etc). These must be filed via the bug report template.
- [x] I have looked through the open issues for a duplicate request.

### What's the problem this feature will solve?

A reusable workflow that uses secrets without declaring them in on.workflow_call.secrets ( https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets ) can't be called without 'secrets-inherit' (I think).

Maybe it would make sense to alert about that also, even if it's one step away from being a security problem?

### Describe the solution you'd like

warn about reusable actions that use secrets without declaring them.

**Comment by woodruffw** [comment]
Hi @alexanderkjall, thanks for opening a feature request.

Could you say more about what you're expecting here? The audit should only warn when the user passes `secrets: inherit`, not when they explicitly forward the secrets the called workflow *should* have access to.

In other words, the audit should flag this:

```yaml
jobs:
  pass-secrets-to-workflow:
    uses: ./.github/workflows/called-workflow.yml
    secrets: inherit
```

but **not** this:

```yaml
jobs:
  pass-secrets-to-workflow:
    uses: ./.github/workflows/called-workflow.yml
    secrets:
      forward-me: ${{ secrets.forward-me }}
      me-too: ${{ secrets.me-too }}
```
