### ISSUE TITLE
Possible Error in Documentation: `actions: read` Permission May Not Be Required for Using `zizmor` in GitHub Actions

### ISSUE THREAD

**Issue by vivodi** [woodruffw/zizmor#608]
[The documentation](https://woodruffw.github.io/zizmor/usage/#use-in-github-actions) states that `zizmor` requires `actions: read` permission when used in GitHub Actions. However, testing suggests that this permission is not actually needed. Additionally, the [GitHub API documentation](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-actions) does not indicate that this permission is necessary.  

Could you confirm whether this requirement is indeed needed, and update the documentation accordingly if it's incorrect?

**Comment by woodruffw** [comment]
> [The documentation](https://woodruffw.github.io/zizmor/usage/#use-in-github-actions) states that zizmor requires actions: read permission when used in GitHub Actions. However, testing suggests that this permission is not actually needed.

Where does the documentation say this? The docs give the following example:

```yaml
name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  zizmor:
    name: zizmor latest via PyPI
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      # required for workflows in private repositories
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Run zizmor 🌈
        run: uvx zizmor --format sarif . > results.sarif 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: zizmor
```

which clearly says that `permissions: read` and `actions: read` are only needed for **private** repositories, not public ones. Did you test this case, or only with public repositories?

(This could perhaps be clarified by duplicating the comment on both lines, instead of just above `contents: read`. I'd be happy to review a PR that improves that.)
