### ISSUE TITLE
[BUG]: Ignoring results with inline comments on composite actions

### ISSUE THREAD

**Issue by moe-ad** [woodruffw/zizmor#612]
### Pre-submission checks

- [x] I am **not** filing a feature request. These should be filed via the feature request form instead.
- [x] I have looked through the [open issues](https://github.com/woodruffw/zizmor/issues?q=is%3Aissue+is%3Aopen+) for a duplicate report.

### Expected behavior

Ignore results within composite actions using inline comments.

### Actual behavior

Results are not ignored when inline comments are used within composite actions.

### Reproduction steps

On a composite action that raises `error[template-injection]` for example, adding `# zizmor: ignore[template-injection]` has no effect.

### Logs

```plain text

```

### Additional context

Kudos for the great work being done @woodruffw.

zizmor is being used to tighten up our actions here: https://github.com/ansys/actions/pull/725
>[!NOTE]
>I am opening this as a bug and not as a feature request because the documentation implies that inline comments should be supported within composite actions. [Although on this page](https://woodruffw.github.io/zizmor/configuration/), it is stated that a `zizmor.yml` config cannot be used. I stand to be corrected though, maybe I missed something. Thanks!

**Comment by temenuzhka-thede** [comment]
Similar experience when running zizmor as part of a reusable workflow, inline ignore settings and zizmor.yml in caller repository are not honored.

**Comment by woodruffw** [comment]
Hi both, thanks for the report. Could you please provide a reproducer case for me? Inline ignore comments should definitely work in all workflow and action definitions, although you're right that configuration-level ignores are currently workflow-only.

**Comment by woodruffw** [comment]
For context, this works as expected for me, i.e. produces no findings except one ignored one:

```yaml
name: test-workflow-ignores

on:
  push:
  workflow_call:

permissions: {}

jobs:
  inject-me:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # zizmor: ignore[template-injection]
        with:
          script: |
            return "${{ github.event.issue.title }}"
```

it also works if you put the ignore comment on an interior element, e.g.:

```yaml
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: | # zizmor: ignore[template-injection]
            return "${{ github.event.issue.title }}"
```

However, what *doesn't* work is if you put the comment within the YAML string itself, e.g.:

```yaml
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          # does not work!
          script: |
            return "${{ github.event.issue.title }}" # zizmor: ignore[template-injection]
```

The reason for this is essentially syntactical: the first two examples are YAML comments, while the third is a *bash comment* that happens to share the same syntax as a YAML comment. `zizmor` handles (most) ignores on the syntactical level of YAML, since we don't know whether arbitrary strings have internal syntaxes that are compatible with YAML.

TL;DR: Your inline ignore comment needs to be somewhere in the YAML syntax tree itself, not within a string literal, since `zizmor` can't analyze the latter. This could probably be documented better within the online docs, and I'd welcome thoughts on how to do that 🙂

**Comment by temenuzhka-thede** [comment]
Hi @woodruffw ,

I have repo A where I define a reusable workflow with zizmor, and repo B (caller repo) from which I call that workflow. There are some private actions that I use within my workflows in repo B, which I would prefer to ignore scanning against some of the online audit rules such as impostor-commit for example, as the GH_TOKEN for my caller workflow does not have the permissions (by design) to make http requests to my private actions repo at https://api.github.com/repos/org/private-actions-repo. Adding an inline ignore comment within the workflow file in repo B, where I call these private actions is not getting honored.

 ```
steps:
  - uses: private-actions-repo/my-action@v1 # zizmor: ignore[impostor-commit]

```
Similarly, defining a zizmor.yml config file in repo B, does not get picked up. If I define one however, in repo A, where my zizmor reusable workflow is defined, that configuration file is picked up.

**Comment by woodruffw** [comment]
Thanks for the additional context!

> There are some private actions that I use within my workflows in repo B, which I would prefer to ignore scanning against some of the online audit rules such as impostor-commit for example, as the GH_TOKEN for my caller workflow does not have the permissions (by design) to make http requests to my private actions repo at [api.github.com/repos/org/private-actions-repo](https://api.github.com/repos/org/private-actions-repo). Adding an inline ignore comment within the workflow file in repo B, where I call these private actions is not getting honored.

There are two different things here: 

1. Disabling a particular audit so that it doesn't produce any results at all;
2. Ignoring the results of an audit _after it has run_.

It sounds like you're trying to do (1) since you have permission limitations, but you're trying to use the ignore machinery, which only does (2). More specifically, the ignore machinery only does (2) because it works by filtering results *after* the audit runs; it can't stop the audit itself from running.

To fix this, you can run `zizmor` with `--no-online-audits`, as documented here: <https://woodruffw.github.io/zizmor/usage/#operating-modes> -- that will perform online collection if you need it, but will disable every audit that needs GitHub API access. Or, if you don't need online access at all, you can run `zizmor` with `--offline` to completely disable all network behavior.

> Similarly, defining a zizmor.yml config file in repo B, does not get picked up. If I define one however, in repo A, where my zizmor reusable workflow is defined, that configuration file is picked up.

This is semi-intentional behavior: zizmor's configuration was originally intended to be global, i.e. per-run instead of per-repository. In practice, this means that remote configs are never loaded, and that you can't "extend" a run's configuration by loading indirect configurations.

I have plans to fix this more generally by introducing a "v2" config format that can be loaded multiple times, once per repository being audited. That's going to require significant architectural changes, however, so I haven't begun on it yet.

**Comment by woodruffw** [comment]
I've opened #614 to fix the documentation side of this -- please take a look and let me know if that further clarifies how ignore comments should be placed.

**Comment by moe-ad** [comment]
@woodruffw Thanks for the detailed explanations.

I followed your guide of adding the comments to the yaml elements, and here are my findings:

Considering the following example:
```yaml
name: "Automerge dependabot and pre-commit.ci PRs"
description: "Action merging dependabot and pre-commit.ci PRs."

inputs:
  approver:
    description: "Approver GitHub ID."
    required: true
    type: string
  approver-token:
    description: "Approver GitHub token."
    required: true
    type: string

runs:
  using: "composite"
  steps:

    - name: Verify allowed PRs (dependabot and pre-commit.ci)
      id: verify-allowed-prs
      shell: bash
      run: |
        # Check if the author is either dependabot or pre-commit.ci.
        if [[ ${{ github.event.pull_request.user.login }} == 'dependabot[bot]' ]] || [[ ${{ github.event.pull_request.user.login }} == 'pre-commit-ci[bot]' ]]; then
        .
        .
        .
```

Comment placed beside the first `key: value` pair in the step sequence works:
```yaml
name: "Automerge dependabot and pre-commit.ci PRs"
description: "Action merging dependabot and pre-commit.ci PRs."

inputs:
  approver:
    description: "Approver GitHub ID."
    required: true
    type: string
  approver-token:
    description: "Approver GitHub token."
    required: true
    type: string

runs:
  using: "composite"
  steps:

    - name: Verify allowed PRs (dependabot and pre-commit.ci)  # zizmor: ignore[template-injection] this works fine
      id: verify-allowed-prs
      shell: bash
      run: |
        # Check if the author is either dependabot or pre-commit.ci.
        if [[ ${{ github.event.pull_request.user.login }} == 'dependabot[bot]' ]] || [[ ${{ github.event.pull_request.user.login }} == 'pre-commit-ci[bot]' ]]; then
        .
        .
        .
```

Comment in front of any other `key: value` pair in the step sequence doesn't work:
```yaml
name: "Automerge dependabot and pre-commit.ci PRs"
description: "Action merging dependabot and pre-commit.ci PRs."

inputs:
  approver:
    description: "Approver GitHub ID."
    required: true
    type: string
  approver-token:
    description: "Approver GitHub token."
    required: true
    type: string

runs:
  using: "composite"
  steps:

    - name: Verify allowed PRs (dependabot and pre-commit.ci)
      id: verify-allowed-prs   # zizmor: ignore[template-injection] this will not work
      shell: bash
      run: |
        # Check if the author is either dependabot or pre-commit.ci.
        if [[ ${{ github.event.pull_request.user.login }} == 'dependabot[bot]' ]] || [[ ${{ github.event.pull_request.user.login }} == 'pre-commit-ci[bot]' ]]; then
        .
        .
        .
```

This may be by design, but maybe it is worth clarifying in the documentation too. Something like `to ignore findings within a single composite action step, inline comments should be placed in front of the first **key: value** pair` should do.
