### ISSUE TITLE
Feature: Use app token for private repos,  GHA's default token for public repos

### ISSUE THREAD

**Issue by arianvp** [woodruffw/zizmor#690]
### Pre-submission checks

- [x] I am **not** reporting a bug (crash, false positive/negative, etc). These must be filed via the bug report template.
- [x] I have looked through the open issues for a duplicate request.

### What's the problem this feature will solve?

I want zizmor to have access to private actions in our org; so I set it up to use an app token that has access to our internal actions repo.

However app tokens can not access **public** repos  so zizmor crashes with

```
Caused by:
    HTTP status client error (401 Unauthorized) for url (https://api.github.com/repos/actions/checkout/tags?page=0&per_page=100)
Error: Process completed with exit code 1.
```

The config:

```yaml
 - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run zizmor 🌈
        # FIXME: fun edge case. A github app token can fetch our private actions, but
        # it can not fetch *public* actions.
        # we now run zizmor in offline mode instead. Which means less features. But can't find a way to
        # make it work otherwise
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}}
        run: |
          nix run --inputs-from . nixpkgs#zizmor -- \
            --format sarif --pedantic . > results.sarif
```

### Describe the solution you'd like

Could we come up with a scheme where Zizmor uses the provided token for private repos; but defaults to `GITHUB_TOKEN` for public ones?
