### ISSUE TITLE
New audit: `unpinned-images`

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#704]
Saving this as an idea.

This would be like `unpinned-uses`, but for `container:` blocks.

For example, this `semgrep` job should be flagged since the container (`semgrep/semgrep`) isn't pinned in any way:

```
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - run: semgrep ci
```
