### ISSUE TITLE
`pull_request_target is almost always used insecurely`

### ISSUE THREAD

**Issue by ljharb** [woodruffw/zizmor#82]
pull_request_target is more secure than pull_request, which is why it gets access to secrets. There's nothing "fundamentally insecure" about it.

Can you elaborate on this?

**Comment by woodruffw** [comment]
Hi @ljharb, thanks for filing an issue.

The docs (<https://woodruffw.github.io/zizmor/audits/#dangerous-triggers>) have some sources for this, but to summarize:

* `pull_request_target` (and `workflow_call`) are somewhat unique in that they're often triggered by third-party users, but have the same *context* as their upstream repo. That means that they have secret and other context access for the upstream repo, rather than the repo sending the PR. There are other triggers that run in "upstream" contexts, but most can only be triggered by that upstream itself (e.g. `push`, since pushing to a repo already implies a degree of access to it).
* *On its own*, this is not an issue. However, users *consistently* misuse `pull_request_target` (and `workflow_call`) in workflows in ways that allow someone to achieve code execution *in the upstream context* just by sending a PR.

The "classic" example of this is documented in a [2021 post from GitHub's security lab](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/):

```yaml
on:
  pull_request_target

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-node@v1
    - run: |
        npm install
        npm build
```

The upstream's *intent* here is (typically) just to install some dependencies. However, because they've checked out attacker-controlled code into the upstream context, `npm install` is fully controlled by the attacker instead, and can exfiltrate the default `GH_TOKEN`, any members of `secrets.*`, etc.

TL;DR: `pull_request_target` runs in the parent repo context but, unlike most parent repo triggers, can be triggered by external users as well. This enables footguns around attacker-controlled code in the parent context that alternative triggers (like `pull_request`) don't allow.

(To my understanding, GitHub is aware of this footgun and considers it a security issue, per the GHSL post above and [warnings in the docs](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target). However, they aren't interested in removing or neutralizing `pull_request_target` because they consider it the user's responsibility to use it correctly. Hence `zizmor` flagging on it.)
