### ISSUE TITLE
How can 'github.ref_name' be attacker controlled?

### ISSUE THREAD

**Issue by ecnepsnai** [woodruffw/zizmor#85]
Given the following example workflow:

```yaml
name: "Example"

on:
  push:
    tags: [ "*" ]

permissions:
  actions: read
  contents: read

jobs:
  build:
    name: "Example"
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "${{ github.ref_name }}"
```

The use of `github.ref_name` will be flagged as being possibly attacker controlled, but I'm genuinely curious how?

My understanding is that this value will only refer to either a commit SHA, or a tag name. People without commit rights can't commit tags, so wouldn't that only leave a commit SHA?
