### ISSUE TITLE
Provide as a GitHub action

### ISSUE THREAD

**Issue by danielrbradley** [woodruffw/zizmor#89]
The example from your own repo is a useful starting point: https://github.com/woodruffw/zizmor/blob/main/.github/workflows/zizmor.yml

However, for users who are only familiar with GitHub Actions and not with cargo, sarif or codeql, it might be nicer to abstract these away behind a github action.

This action could either be shipped within this same repo, or as a standalone repo. The usage could look something like:

```yml
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: woodruffw/zizmor@v1
        with:
          # Optional. Defaults to "^0.1.4"
          version: "^0.1.4"
          # Optional. Defaults to "." to auto-discover workflows in the current repo
          path: "."
```
